#!/bin/bash
# deploy.sh — Build, deploy to /Applications, and launch Pinchr
# Usage: ./deploy.sh
set -e

APP_NAME="Pinchr"
DIST_APP="dist/mac-arm64/${APP_NAME}.app"
INSTALL_APP="/Applications/${APP_NAME}.app"
CACHE_DIR="$HOME/Library/Application Support/pinchr"
NODE_PATH="/Users/drewwagner/.nvm/versions/node/v20.19.4/bin"

echo "🦞 Pinchr Deploy"
echo "================"

# 1. Kill any running Pinchr
echo "⏹  Killing ${APP_NAME}..."
pkill -9 -f "${APP_NAME}" 2>/dev/null || true
sleep 2
# Verify it's dead
if pgrep -f "${APP_NAME}" > /dev/null 2>&1; then
    echo "⚠️  Force killing remaining processes..."
    pkill -9 -f "${APP_NAME}" 2>/dev/null || true
    sleep 2
fi
echo "   ✅ No ${APP_NAME} processes running"

# 2. Stamp build hash into environment
BUILD_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date +"%Y-%m-%d %H:%M:%S")
echo "📦 Build: ${BUILD_HASH} at ${BUILD_TIME}"

# Write build info for the renderer to read
cat > src/renderer/src/buildInfo.ts << EOF
// Auto-generated by deploy.sh — do not edit
export const BUILD_HASH = '${BUILD_HASH}'
export const BUILD_TIME = '${BUILD_TIME}'
EOF

# 3. Set notarization credentials from environment
# Required: APPLE_ID, APPLE_ID_PASS, APPLE_TEAM_ID
if [ -z "${APPLE_ID:-}" ] || [ -z "${APPLE_ID_PASS:-}" ]; then
    echo "⚠️  APPLE_ID and APPLE_ID_PASS not set — notarization will be skipped"
fi
export APPLE_TEAM_ID="${APPLE_TEAM_ID:-8RZNRHSN39}"

# 3. Clean build
echo "🔨 Building (with notarization)..."
rm -rf out/ dist/
PATH="${NODE_PATH}:$PATH" yarn dist 2>&1 | tail -10

if [ ! -d "$DIST_APP" ]; then
    echo "❌ Build failed — $DIST_APP not found"
    exit 1
fi
echo "   ✅ Build complete"

# 4. Deploy to /Applications
echo "📋 Deploying to /Applications..."
rm -rf "$INSTALL_APP"
cp -R "$DIST_APP" "$INSTALL_APP"

# Verify
if strings "$INSTALL_APP/Contents/Resources/app.asar" | grep -q "$BUILD_HASH"; then
    echo "   ✅ Build ${BUILD_HASH} verified in /Applications"
else
    echo "   ⚠️  Build hash not found in asar (might be fine for non-renderer changes)"
fi

# 5. Clear Electron caches
echo "🧹 Clearing caches..."
rm -rf "$CACHE_DIR/Cache" "$CACHE_DIR/Code Cache" "$CACHE_DIR/GPUCache" "$CACHE_DIR/Service Worker" 2>/dev/null
echo "   ✅ Caches cleared"

# 6. Launch (with CDP for self-testing)
echo "🚀 Launching ${APP_NAME} (CDP on port 9222)..."
open "$INSTALL_APP" --args --remote-debugging-port=9222

echo ""
echo "✅ Deploy complete: ${BUILD_HASH} (${BUILD_TIME})"
echo "   Running from: ${INSTALL_APP}"
echo "   CDP: http://127.0.0.1:9222"
echo "   Self-test: npx tsx scripts/self-test.ts"
