export type Page =
  | 'dashboard'
  | 'chat'
  | 'sessions'
  | 'tasks'
  | 'automations'
  | 'skills'
  | 'connections'
  | 'brain'
  | 'memory-explorer'
  | 'terminal'
  | 'settings'
  | 'onboarding'
  | 'support'
